services:
    redis:
      image: redis:latest
    bot:
      image: 'moderator_bot'
      environment:
        REDIS_URL: redis://redis:6379/3
      volumes:
        - /Users/rejoller/persik_bot/persik_bot/data_sources/saved_data:/app/data_sources/vacation/
        - /Users/rejoller/persik_bot/persik_bot/bot_log/:/app/bot_log/
        
      restart: "always"
      depends_on:
        - redis